apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-time-service
spec:
  selector:
    matchLabels:
      app: ts-time-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-time-service
    spec:
      containers:
        - name: ts-time-service
          image: codewisdom/ts-time-service:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          envFrom:
            - configMapRef:
                name: nacos
          ports:
            - containerPort: 12346
            - containerPort: 32697
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 500m
              memory: 2000Mi
          readinessProbe:
            tcpSocket:
              port: 12346
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ts-time-service
spec:
  type : NodePort
  ports:
    - name: http
      port: 12346
    - name: debug
      port: 32697
      nodePort: 32691
  selector:
    app: ts-time-service